// ============================================================
// DENTORA AI - BDS Final Year Subjects (RGUHS / Standard)
// Pre-seeded for Meghna Institute of Dental Sciences
// ============================================================

export const BDS_FINAL_YEAR_SUBJECTS = [
  {
    code: "OM",
    name: "Oral Medicine and Radiology",
    color: "#3b82f6",
    total_topics: 42,
    exam_weightage: 20,
    key_topics: [
      "Diseases of oral mucosa",
      "Salivary gland disorders",
      "Temporomandibular joint disorders",
      "Oral manifestations of systemic diseases",
      "Radiographic interpretation",
      "Dental and maxillofacial radiology",
      "Radiation safety",
      "Pigmented lesions",
      "Vesiculobullous lesions",
      "White lesions of oral cavity",
    ],
  },
  {
    code: "OS",
    name: "Oral Surgery",
    color: "#ef4444",
    total_topics: 38,
    exam_weightage: 20,
    key_topics: [
      "Exodontia – principles and techniques",
      "Surgical anatomy",
      "Local anesthesia",
      "Impacted teeth",
      "Preprosthetic surgery",
      "Cysts of jaw",
      "Tumors of jaw",
      "Fractures of jaw",
      "Temporomandibular disorders",
      "Infections of oral and maxillofacial region",
    ],
  },
  {
    code: "PDC",
    name: "Pedodontics and Preventive Dentistry",
    color: "#10b981",
    total_topics: 35,
    exam_weightage: 15,
    key_topics: [
      "Child psychology and behavior management",
      "Caries in children",
      "Pulp therapy in primary teeth",
      "Space maintainers",
      "Oral habits",
      "Pit and fissure sealants",
      "Fluoride",
      "Preventive orthodontics",
      "Traumatic injuries in children",
      "Special needs dentistry",
    ],
  },
  {
    code: "OPT",
    name: "Orthodontics and Dentofacial Orthopaedics",
    color: "#8b5cf6",
    total_topics: 40,
    exam_weightage: 15,
    key_topics: [
      "Growth and development",
      "Cephalometrics",
      "Malocclusion classification",
      "Etiology of malocclusion",
      "Orthodontic appliances",
      "Fixed appliance therapy",
      "Removable appliances",
      "Retention and relapse",
      "Orthopedic appliances",
      "Surgical orthodontics",
    ],
  },
  {
    code: "PER",
    name: "Periodontics",
    color: "#f59e0b",
    total_topics: 36,
    exam_weightage: 15,
    key_topics: [
      "Anatomy of periodontium",
      "Gingival diseases",
      "Periodontitis classification",
      "Systemic factors affecting periodontium",
      "Periodontal examination",
      "Non-surgical periodontal therapy",
      "Surgical periodontal therapy",
      "Regenerative procedures",
      "Periodontal emergencies",
      "Implantology basics",
    ],
  },
  {
    code: "PR",
    name: "Prosthodontics and Crown & Bridge",
    color: "#06b6d4",
    total_topics: 44,
    exam_weightage: 15,
    key_topics: [
      "Complete denture prosthodontics",
      "Removable partial dentures",
      "Implant-supported prostheses",
      "Fixed partial dentures",
      "Crown preparations",
      "Impression materials",
      "Occlusion",
      "Jaw relation records",
      "Denture base materials",
      "Maxillofacial prosthetics",
    ],
  },
  {
    code: "CDE",
    name: "Conservative Dentistry and Endodontics",
    color: "#f97316",
    total_topics: 45,
    exam_weightage: 20,
    key_topics: [
      "Caries etiology and classification",
      "G.V. Black's cavity classification",
      "Dental materials – composites, GIC, amalgam",
      "Pulp biology and pathology",
      "Access opening and biomechanical preparation",
      "Obturation techniques",
      "Root canal irrigants and medicaments",
      "Bleaching of teeth",
      "Restoration of endodontically treated teeth",
      "Retreatment and surgical endodontics",
    ],
  },
  {
    code: "PHD",
    name: "Public Health Dentistry",
    color: "#84cc16",
    total_topics: 30,
    exam_weightage: 10,
    key_topics: [
      "Epidemiology of dental caries",
      "Epidemiology of periodontal diseases",
      "Fluoride and fluorosis",
      "Water fluoridation",
      "Dental indices – DMFT, CPITN, OHI-S",
      "Community dental health programs",
      "Oral health surveys",
      "Health education and promotion",
      "Nutrition and oral health",
      "National oral health policy",
    ],
  },
] as const;

export const SPACED_REPETITION_INTERVALS = [1, 3, 7, 15, 30, 60] as const;

export const EXAM_MODES = [
  { value: "beginner", label: "Beginner", description: "Guided hints, simpler questions" },
  { value: "intermediate", label: "Intermediate", description: "Standard exam-level questions" },
  { value: "exam", label: "Exam Mode", description: "No hints, strict evaluation" },
  { value: "mock_external", label: "Mock External", description: "Simulates university external examiner" },
] as const;

export const ACHIEVEMENT_LIST = [
  { name: "First Login", icon: "🎉", xp: 50, description: "Welcome to Dentora AI!" },
  { name: "Study Starter", icon: "📚", xp: 100, description: "Complete your first study session" },
  { name: "3-Day Streak", icon: "🔥", xp: 150, description: "Study 3 days in a row" },
  { name: "Week Warrior", icon: "⚡", xp: 300, description: "Study 7 days in a row" },
  { name: "Viva Victor", icon: "🎤", xp: 200, description: "Complete your first viva session" },
  { name: "Flash Master", icon: "⚡", xp: 250, description: "Review 100 flashcards" },
  { name: "Paper Hunter", icon: "📄", xp: 200, description: "Analyze your first previous paper" },
  { name: "Night Owl", icon: "🦉", xp: 100, description: "Study session after 10 PM" },
  { name: "Early Bird", icon: "🌅", xp: 100, description: "Study session before 7 AM" },
  { name: "Topic Terminator", icon: "✅", xp: 500, description: "Complete all topics in a subject" },
  { name: "Exam Ready", icon: "🏆", xp: 1000, description: "Reach 90% readiness score" },
  { name: "AI Scholar", icon: "🤖", xp: 150, description: "Complete 10 AI tutor sessions" },
] as const;
